package com.mycompany.myapp;

import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.table.TableLayout;
import com.codename1.ui.util.Resources;

import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class Choices {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        this.theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
        if (this.current != null) {
            this.current.show();
            return;
        }

        /*
         * Form hi = new Form("Hi World"); hi.addComponent(new Label("Hi World"
         * )); hi.show();
         */

        TableLayout t1;
        int spanButton = 2;
        Form hi = new Form();
        t1 = new TableLayout(9, 1);
        t1.setGrowHorizontally(true);
        hi.setLayout(t1);

        TextField firstName = new TextField("", "First Name", 20, TextArea.ANY);
        TextField stateName = new TextField("", "State", 20, TextArea.ANY);
        TextField genderName = new TextField("", "Gender", 20, TextArea.ANY);
        TextField raceName = new TextField("", "Race", 20, TextArea.ANY);
        Button submit = new Button("Submit");
//        ComboBox<Map<String, Object>> stateCombo = new ComboBox<> (
        //             createListEntry("Alabama", "dsa")
        // createListEntry("Alaska", "Wow")
        //);

        TableLayout.Constraint cn = t1.createConstraint();
        cn.setHorizontalSpan(spanButton);
        cn.setVerticalSpan(Component.RIGHT);

        hi.add("First Name").add(firstName);
        hi.add("State").add(stateName);
        hi.add("Gender").add(genderName);
        hi.add("Race").add(raceName);
        hi.add(submit);

        submit.setHidden(true);
        hi.show();

        submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent submitPressed) {

                String name = firstName.getText();

                String state = stateName.getText();
                String gender = genderName.getText();
                String race = raceName.getText();

                SimpleWriter nameOut = new SimpleWriter1L("data/name.txt");
                SimpleWriter stateOut = new SimpleWriter1L("data/state.txt");
                SimpleWriter genderOut = new SimpleWriter1L("data/gender.txt");
                SimpleWriter raceOut = new SimpleWriter1L("data/race.txt");

                nameOut.println(name);
                stateOut.println(state);
                genderOut.println(gender);
                raceOut.println(race);

            }
        });

    }

    public void stop() {
        this.current = Display.getInstance().getCurrent();
        if (this.current instanceof Dialog) {
            ((Dialog) this.current).dispose();
            this.current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
